name: toffy_env
dependencies:
  - python=3.8
  - pip
  - pip:
    - ark-analysis>=0.3.0,<=0.4.0
    - git+https://github.com/angelolab/mibi-bin-tools.gitv0.2.2
    - jupyter>=1.0.0,<2
    - jupyter_contrib_nbextensions>=0.5.1,<1
    - jupyterlab>=3.4.3,<4
    - watchdog>=2.1.6,<3
    - natsort >= 0.8
    - numpy>=1.22,<2
