name: toffy_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - seaborn
  - scikit-learn
  - jupyterlab
  - jupyter_contrib_nbextensions
  - pip:
    - natsort
    - watchdog
    - mibi-bin-tools
    - toffy==0.1.3
