name: toffy_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - seaborn
  - scikit-learn
  - jupyterlab
  - jupyter_contrib_nbextensions
  - pip:
    - natsort
    - watchdog
    - alpineer==0.1.7
    - mibi-bin-tools==0.2.9
    - toffy==0.2.0
