name: toffy_env
dependencies:
  - python=3.8
  - pip
  - pip:
    - git+https://github.com/angelolab/mibi-bin-tools.git@02b4549731c2204e727073d6f23d3a91123e69d8
    - git+https://github.com/angelolab/ark-analysis.git@master
    - jupyter>=1.0.0,<2
    - jupyter_contrib_nbextensions>=0.5.1,<1
    - jupyterlab>=3.1.5,<4
    - watchdog>=2.1.6,<3
    - numpy>=1.22,<2
