name: toffy_env
dependencies:
  - python=3.8
  - pip
  - pip:
    - git+https://github.com/angelolab/mibi-bin-tools.git@v0.2.5
    - git+https://github.com/angelolab/tmi.git@v0.0.1
    - jupyter>=1.0.0,<2
    - jupyter_contrib_nbextensions>=0.5.1,<1
    - jupyterlab>=3.4.3,<4
    - natsort>=0.8
    - numpy>=1.22,<2
    - seaborn>=0.12.1,<1
    - scikit-learn>=1.1.3,<2
    - traitlets>=5.2.2
    - watchdog>=2.1.6,<3
