# Formatting and Linting
line-length = 110
select = [
    "D", # pydocstyle
    "E", # pycodestyle Error
    "W", # pycodestyle Warning
    "F", # Pyflakes
    "I", # isort
]
ignore = ["D100", "I001", "D103", "D205", "D104", "F401", "F811"]
fixable = ["A", "B", "D", "E", "F", "W"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Assume Python 3.10
target-version = "py310"

[mccabe]
max-complexity = 10

[pycodestyle]
max-doc-length = 110

[pydocstyle]
convention = "google"
